# Generated by Django 4.0.6 on 2023-07-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('encrypted_dummy', models.CharField(max_length=255)),
                ('public_key', models.CharField(max_length=255)),
                ('encrypted_private_key', models.CharField(max_length=255)),
            ],
        ),
    ]
