# Generated by Django 4.0.6 on 2023-07-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='encrypted_dummy',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='encrypted_private_key',
            field=models.BinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_key',
            field=models.BinaryField(max_length=255),
        ),
    ]
